autoficate/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
import os

from main.views import IndexView, Custom404View, LogoutView, SignupView

from django.conf.urls import handler404

handler404 = Custom404View

urlpatterns = [
    path(f'{os.environ.get("ADMIN_PATH")}/', admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("signup/", SignupView, name="signup"),
    path("logout/", LogoutView, name="logout"),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.utils import timezone
from django.contrib.auth.models import BaseUserManager, AbstractUser
from django.db import models
from django.utils.crypto import get_random_string
from django.conf import settings
from django.db import models
from django.core.cache import cache
from django.core.serializers import serialize
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
import ast
import os
from django.conf import settings


import os


class CustomUserManager(BaseUserManager):
    def create_user(self, user_email, password=None, **extra_fields):
        if not user_email:
            raise ValueError("The Email field must be set")
        user = self.model(user_email=self.normalize_email(user_email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, user_email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("first_name", str(user_email.split("@")[0]))
        extra_fields.setdefault("last_name", "admin")
        return self.create_user(user_email, password, **extra_fields)


class CustomUser(AbstractUser):
    user_id = models.BigAutoField(primary_key=True)
    groups = models.ManyToManyField(
        "auth.Group",
        related_name="customuser_groups",
        related_query_name="customuser_group",
        blank=True,
        verbose_name="groups",
        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
    )
    user_permissions = models.ManyToManyField(
        "auth.Permission",
        related_name="customuser_permissions",
        related_query_name="customuser_permission",
        blank=True,
        verbose_name="user permissions",
        help_text="Specific permissions for this user.",
    )
    user_email = models.EmailField(
        max_length=255,
        verbose_name="User Email",
        unique=True,
        blank=True,
    )
    unique_code = models.CharField(
        max_length=4,
        editable=False,
        unique=True,
        null=False,
    )

    allow_promotional = models.BooleanField(
        blank=False, default=False, editable=True, null=False
    )

    objects = CustomUserManager()

    USERNAME_FIELD = "user_email"
    EMAIL_FIELD = "user_email"
    REQUIRED_FIELDS = []

    def save(self, *args, **kwargs):
        if not self.unique_code:
            unique_code = get_random_string(
                length=4, allowed_chars="bcfghklmopqrsuwxyz0123456789"
            )

            while CustomUser.objects.filter(unique_code=unique_code).exists():
                unique_code = get_random_string(
                    length=4, allowed_chars="bcfghklmopqrsuwxyz0123456789"
                )

            self.unique_code = unique_code

        if not self.username:
            self.username = f"{self.first_name}-{self.last_name}-{self.unique_code}"

        super().save(*args, **kwargs)

    def update_password(self, new_password):
        self.set_password(new_password)
        self.save()

    def __str__(self):
        return self.username

    class Meta:
        verbose_name_plural = "Custom Users"

class DataItemSetModelManager(models.Manager):
    def get_header_cache_key(self, user_code):
        return f"header_cache_{user_code}"

    def get_item_cache_key(self, item_set_heading):
        return f"item_cache_{item_set_heading}"

    def reload_header_cache(self, user_code):
        try:
            inspector_header = list(
                self.filter(user_code=user_code).values_list("item_set_heading", flat=True)
            )

            cache.set(self.get_header_cache_key(user_code), inspector_header)

        except ObjectDoesNotExist as e:
            print(f"reload_header_cache: {e}")

    def reload_item_cache(self, item_set_heading):
        try:
            inspector_data = ast.literal_eval(
                self.get(item_set_heading=item_set_heading).item_set
            )

            cache.set(self.get_item_cache_key(item_set_heading), inspector_data)

        except ObjectDoesNotExist as e:
            print(f"reload_item_cache: {e}")

    def reload_cache(self, user_code, headers, header_items, clear_cache=False):
        if headers:
            if clear_cache:
                cache.delete(self.get_header_cache_key(user_code))
            self.reload_header_cache(user_code)
            return

        if header_items is None:
            header_items = cache.get(self.get_header_cache_key(user_code))

        for item in header_items:
            if clear_cache:
                cache.delete(self.get_item_cache_key(item))
            self.reload_item_cache(item)

class DataItemSetModel(models.Model):
    item_set_id = models.BigAutoField(primary_key=True)

    # objects = DataItemSetModelManager()

    item_set_heading = models.CharField(
        max_length=255,
        verbose_name="Item Data Set Heading",
    )
    item_set = models.TextField(
        verbose_name="Item Data Set List",
        default="[""]"
    )

    position_x = models.PositiveIntegerField(
        default=0,
    )
    position_y = models.PositiveIntegerField(
        default=0,
    )
    font_size = models.PositiveIntegerField(
        default=12,
    )
    font_name = models.CharField(
        max_length=255,
        unique=False,
        default="arial",
        verbose_name="Font Name",
    )
    color = models.CharField(
        max_length=9,
        unique=False,
        default="#aa33ffff",
        verbose_name="Text Color",
    )

    user_code = models.CharField(
        max_length=4,
        editable=False,
        unique=False,
        null=False,
    )
    created = models.DateTimeField(
        null=True,
    )

    # @staticmethod
    def search_font(font_name):
        font_path = os.path.join(settings.STATIC_ROOT, "fonts", f"{font_name}.ttf")

        if os.path.exists(font_path):
            return font_path
        else:
            return None

    def save(self, *args, **kwargs):
        # Clear cache on save
        if not self.created:
            self.created = timezone.now()

        # cache.delete(self.objects.get_header_cache_key(self.user_code))
        # cache.delete(self.objects.get_item_cache_key(self.item_set_heading))

        super().save(*args, **kwargs)

    def __str__(self):
        if len(self.item_set) >= 25:
            return f"{self.item_set[:25]}..."
        else:
            return self.item_set

    class Meta:
        verbose_name_plural = "DataItem Set Models"


class ImageModel(models.Model):
    image_id = models.BigAutoField(primary_key=True)

    image_file_name = models.CharField(
        max_length=256,
        verbose_name="Background Image Name",
    )
    
    image_url = models.TextField(
        verbose_name="Background Image URL",
    )
    
    preview_image_url = models.TextField(
        verbose_name="Preview Image URL",
        null=True,
    )
    
    export_image_count = models.PositiveIntegerField(
        default=0,
    )
    exports = models.PositiveIntegerField(
        default=0,
    )
    user = models.OneToOneField(
        CustomUser,
        on_delete=models.CASCADE,
        unique=True,
    )

    def delete(self, *args, **kwargs):
        if self.image:
            storage, path = self.image.storage, self.image.path
            storage.delete(path)

        super().delete(*args, **kwargs)

    def __str__(self):
        return self.image_file_name

    class Meta:
        verbose_name_plural = "Image Models"

templates/Custom404.html
<!DOCTYPE HTML>
<html>
<body>
    <h1>404</h1>
</body>
</html>

templates/index.html
{% load static %} 
<!DOCTYPE HTML>
<html>
<head>
    <!-- Include Spectrum CSS -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.8.1/spectrum.min.css">

    <!-- Include jQuery (required for Spectrum) -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    <!-- Include Spectrum JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/spectrum/1.8.1/spectrum.min.js"></script>

    <style>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    </style>
</head>
<body>
    <div>
        Session Name: {{ request.session.user_name }}<br>
        Session Code: {{ request.session.user_code }} <br>
        New User: {{ new_user }}<br>
        Verified: {{ request.session.is_verified }}<br><br>
        Cookie Consent: {{ request.session.cookie_consent }} 
        set_cookie: {{ set_cookie }}
    </div>

    {% if request.session.cookie_consent and set_cookie %}
        <h5>Logic To Set Cookie Will Execute Here...</h5>
        Cookie Key: {{ cookie_key }}
        Cookie Data(Encry): {{ cookie_data }}
        Cookie Data(Decry): {{ cookie_data_temp }}
    {% endif %}

    {% if not new_user and request.session.cookie_consent is None %}
        <form method="post">
            {% csrf_token %}
            Allow Cookies <br> <button type="submit" name="allow_cookies" value="True">Allow</button>    <button type="submit" name="allow_cookies" value="False">Don't Allow</button><br>
        </form>
    {% endif %}

    {% if new_user %}
        <div>
            <hr>
            New User:
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {% if name_signup_form_errors.has_error %}
                    <br>{{ name_signup_form_errors.error.advanced }} <br>
                {% endif %}
                
                First Name: {{ name_signup_form.first_name }}<br>
                Last Name: {{ name_signup_form.last_name }} <br>
                Email (optional): {{ name_signup_form.user_email }} <br>
                
                <button type="submit" name="submit_name_signup" value="name_signup">Submit</button>
            </form>
        </div>
    {% endif %} 

    {% if not request.session.is_verified %}
        <div>
            <hr>
            Login:
            <form method="post">
                {% csrf_token %}
                
                {% if login_form_errors.has_error %}
                    <br>{{ login_form_errors.error.advanced }} <br>
                {% endif %}
                
                Email: {{ login_form.user_email }}<br>
                Password: {{ login_form.password }} <br>
                
                <button type="submit" name="login" value="login">Submit</button>
            </form>
        </div>
    {% endif %}

    {% if request.session.user_code is not None and not new_user or request.session.user_code is not None and request.session.is_verified %}
        <div>
            <hr>
            Item Input:
            <form method="post">
                {% csrf_token %}

                {% if item_form_errors.has_error %}
                    <br>{{ item_form_errors.error.advanced }}<br>
                {% endif %}
                
                Item Name: {{ item_form.item_heading }}<br>
                Position: {{ item_form.position_x }}&nbsp;&nbsp;&nbsp;{{ item_form.position_y }}<br>
                Size: {{ item_form.font_size }}<br>
                Font: {{ item_form.font_select }}<br>
                Color: {{ item_form.color }} <input type="text" name="color_picker" id="id_color_picker"><br>
                
                <button type="submit" name="submit_update" value="update_item_heading">Update Item</button>
                <button type="submit" name="submit_add" value="add_blank_item_heading">+</button>
            </form>
        </div>

        <div>
            <hr>
            Excel File Upload:
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {% if excel_form_errors.has_error %}
                    <br>{{ excel_form_errors.error.advanced }} <br>
                {% endif %}

                Status: {{ excel_file_status }} <br>
                Excel Filename: {{ request.session.excel_file_name }} <br><br>
                
                {{ excel_form.excel_file }} <br>

                <button type="submit" name="submit" value="load_excel_submit">Submit</button>
            </form>
        </div>

        <div>
            <hr>
            Image Upload:
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {% if image_form_errors.has_error %}
                    <br>{{ image_form_errors.error.advanced }} <br>
                {% endif %}

                Image Filename: {{ request.session.image_file_name }}<br>
                Image URL: {{ request.session.image_url }}<br>
                Image Render URL: {{ request.session.preview_url }}<br>

                {% if request.session.preview_url or request.session.preview_url %}
                    <img style="mix-blend-mode: multiply;" src="{% if request.session.preview_url == '' or request.session.preview_url is None %}{{ request.session.image_url }}{% else %}{{ request.session.preview_url }}{% endif %}" /> <br><br>
                {% endif %}

                {{ image_form.image }} <br>

                <button type="submit" name="submit" value="load_image_submit">Submit</button>
            </form>
        </div>

        <div>
            <hr><br>
            Input List Window:
            {% if request.session.inspector_header %}
                {% for header in request.session.inspector_header %}
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="header_item" value="{{ header }}">
                    <button type="submit" name="inspector_header_item" value="{{ header }}">{{ header }}</button>&nbsp;&nbsp;
                    <button type="submit" name="submit_remove" value="inspector_header_item_remove">-</button><br>
                </form>
                {% endfor %}
            {% else %}
                <br><br>No Data Available<br><br>
            {% endif %}
        </div>

        <div>
            <hr><br>
            Inspector Panel:

            <form method="post">
                {% csrf_token %}
                
                {% if inspector_data %}
                    {% for item in inspector_data %}
                        <input type="text" name="inspector_data_item" required value="{{ item }}">&nbsp;&nbsp;
                        <button type="button" name="button" value="inspector_data_item_remove">-</button><br>
                    {% endfor %}
                    
                    {% if not full_available %}
                        .<br>.<br>.<br><button type="submit" name="submit" value="load_all_inspector_data">Load all</button><br>
                    {% endif %}
                    
                    {% comment %} 
                    sample input types to add for a new item (on pressing '+')
                        
                        <input type="text" name="inspector_data_item_new" required value="{{ item }}">&nbsp;&nbsp;
                        <button type="button" name="button" value="inspector_data_item_remove">-</button><br>

                    if the user asks to add these items at the top of the data set
                    include this

                        <input type="hidden" name="inspector_data_item_location" value="top">
                        
                    else for the default bottom
                    include this
                        
                        <input type="hidden" name="inspector_data_item_location" value="bottom">
                            
                        {% endcomment %}
                <input type="hidden" name="inspector_data_item_location" value="top">

                {% endif %}

                {% if not inspector_data %}
                    <br>No Data Available<br>
                {% endif %}
                
                {% if request.session.inspector_header %}
                    <br><button type="buttom" name="button" value="inspector_data_item_add">+</button>&nbsp;&nbsp;
                {% endif %}
                
                {% if inspector_data %}
                    <button type="submit" name="submit" value="update_inspector_data">Update Data</button><br><br>
                {% endif %}
            </form>
        </div>
        <div>
            <hr>
            Export:
            <form method="post">
                {% csrf_token %}

                {% if export_form_errors.has_error %}
                    {{ export_form_errors.error.advanced }}<br>
                {% endif %}

                {{ export_form.export_format }}<br>
                <button type="submit" name="submit" value="export_images">Export</button><br>
            </form>
        </div>

        <div>
            <hr>
            Logout:
            <form action="/logout/" method="get">
                <button type="submit" name="logout" value="logout">Logout</button><br>
            </form>
        </div>
    {% endif %}

    <script>
        // When the document is ready
        $(document).ready(function () {
            // Initialize Spectrum color picker
            $('#id_color_picker').spectrum({
                preferredFormat: "hexa", // Use the hexa format (including alpha)
                showInput: true,
                showPalette: true,
                chooseText: "Select",
                cancelText: "Cancel",
                showInitial: true,
                showAlpha: true,
                maxSelectionSize: 4,
                allowEmpty: false,
                showButtons: false,
                palette: [],
            });
            
            {% if format_reverse %}
                // Set Spectrum color picker's initial color value based on the value of the color input
            
                {% comment %} var initialColorVal = ; {% endcomment %}
                $('#id_color_picker').spectrum("set", $('#id_color').val());

                var hexString = $('#id_color_picker').spectrum("get").toHex8();
                $('#id_color').val('#' + hexString.substring(2) + hexString.substring(0, 2));
                console.log($('#id_color').val());
            {% endif %}
            

            // Handle Spectrum's color change event
            $('#id_color_picker').on('move.spectrum', function (e, color) {
                // Update the color input with the rearranged format
                var hexString = color.toHex8();
                $('#id_color').val('#' + hexString.substring(2) + hexString.substring(0, 2));
            });
    
            // Handle the input event on the color input
            $('#id_color').on('input', function () {
                var newColor = $(this).val();
                // Set Spectrum's color with the rearranged format
                $('#id_color_picker').spectrum("set", newColor.substring(7) + newColor.substring(1, 7));
            });
        });
    </script>
    
</body>
</html>

templates/signup.html
{% load static %} 

<!DOCTYPE HTML>

<HTML>

    <form method="post">
        {% csrf_token %}
		
		{{signup_form_errors}}<br>

        {{ signup_form.first_name.label_tag }} {{ signup_form.first_name }}<br>
    	{{ signup_form.last_name.label_tag }} {{ signup_form.last_name }}<br>
        {{ signup_form.user_email.label_tag }} {{ signup_form.user_email }}<br>
        {{ signup_form.password1.label_tag }} {{ signup_form.password1 }}<br>
        {{ signup_form.password2.label_tag }} {{ signup_form.password2 }}<br><br>
        Opt-in for Mail {{ signup_form.allow_promotional }}<br>
		<br>

        <button type="submit">Sign up</button>
    </form>

</HTML>